### ISSUE TITLE
Where to put config if used inside current NodeJS app

### ISSUE THREAD

**Issue by grinono** [zhr85210078/node-mongodb-es-connector#3]
if i import this npm package on the server. Where to declare the setting variables? and run the package?

**Comment by zhr85210078** [comment]
Hi,this is my nodejs project on the hapi framework.
![6ae2f5e6c74f84bf](https://user-images.githubusercontent.com/6679623/35726963-9031a11e-0841-11e8-9233-79bc7d0b7200.jpg)
First,this is my app.js
![10d537e3f8a7e936](https://user-images.githubusercontent.com/6679623/35727087-e990115a-0841-11e8-8bed-e4ac7c8a57be.jpg)
Second,this is my scheduler
![6c181b947bfd7aeb](https://user-images.githubusercontent.com/6679623/35727123-039b7b66-0842-11e8-93da-779940b8db0c.jpg)
Last,this is my api
![228a2edd18344204](https://user-images.githubusercontent.com/6679623/35727139-0ead1cbc-0842-11e8-95eb-9ca3f853bd10.jpg)
![54f62f85ffbc2af8](https://user-images.githubusercontent.com/6679623/35727144-10c69960-0842-11e8-839c-bef122a9b129.jpg)

I would like to be able to help you.

**Comment by zhr85210078** [comment]
https://github.com/zhr85210078/es-connector-api
